export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const CHANGE_OPTION = "CHANGE_OPTION";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const UPDATE_RESULTS = "UPDATE_RESULTS";
export const UPDATE_PAGINATION = "UPDATE_PAGINATION";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_FILTERS = "CHANGE_FILTERS";
export const CHANGE_PARAMS = "CHANGE_PARAMS";
