import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';

// Generated by create-react-app
ReactDOM.render(
    <App />,
  document.getElementById('root')
);